# General rclone variables.
rclone:
  rclone_config: "$HOME/.config/rclone/rclone.conf"
  rc_user: "user"
  rc_pass: "pass"
  ip: 127.0.0.1
# Global variables
global:
  minjs: 1
  maxjs: 16
  nextjs: 1
  json_dir: "/opt/sa/feederboxsa"
  sleeptime: 15m
# Log variables
log:
  log_dir: "/opt/sarotate/logs/"
  log_file: "/opt/sarotate/logs/sarotate.log"
  notif: "none"
  notif_cmd: "apprise"
# When filling these out you need to make sure the order of remote/port goes together or else 
# the script will read wrong input/output and give errors.
main:
  remote:
   - anime
   - movies
   - tv1
   - tv2
  port:
   - 5575
   - 5576
   - 5577
   - 5578
